{{- if and .Values.vminsert.enabled .Values.vminsert.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.vminsert.ingress.annotations }}
  annotations:
{{ toYaml .Values.vminsert.ingress.annotations | indent 4 }}
{{- end }}
  labels:
  {{- include "victoria-metrics.vminsert.labels" . | nindent 4 }}
{{ toYaml .Values.vminsert.ingress.extraLabels | indent 4 }}
  name: {{ template "victoria-metrics.vminsert.fullname" . }}
spec:
  rules:
  {{- $serviceName := include "victoria-metrics.vminsert.fullname" . }}
  {{- range .Values.vminsert.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
        - path: {{ .path }}
          backend:
            serviceName: {{ $serviceName }}
            servicePort: http
  {{- end -}}
{{- if .Values.vminsert.ingress.tls }}
tls:
{{ toYaml .Values.vminsert.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
