{{- if and .Values.vmstorage.enabled .Values.vmstorage.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- if .Values.vmstorage.serviceMonitor.annotations }}
  annotations:
{{ toYaml .Values.vmstorage.serviceMonitor.annotations | indent 4 }}
  {{- end }}
  labels:
  {{- include "victoria-metrics.vmstorage.labels" . | nindent 4 }}
{{ toYaml .Values.vmstorage.serviceMonitor.extraLabels | indent 4 }}
  name: {{ template "victoria-metrics.vmstorage.fullname" . }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "victoria-metrics.vmstorage.matchLabels" . | nindent 6 }} 
  endpoints:
    - port: http
      {{- if .Values.vmstorage.serviceMonitor.interval }}
      interval: {{ .Values.vmstorage.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.vmstorage.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.vmstorage.serviceMonitor.scrapeTimeout }}
      {{- end }}
  {{- end }}
