version: '3.5'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.3.2
    depends_on:
    - "vminsert"
    - "vmselect"
    ports:
      - 9090:9090
    volumes:
      - promdata:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - docker_net
    restart: always
  vmstorage:
    container_name: vmstorage
    image: victoriametrics/vmstorage:v1.25.1-cluster
    ports:
      - 8482:8482
      - 8400:8400
      - 8401:8401
    volumes:
      - strgdata:/storage
    command:
      - '--storageDataPath=/storage'
    networks:
    - docker_net
    restart: always
  vminsert:
    container_name: vminsert
    image: victoriametrics/vminsert:v1.25.1-cluster
    depends_on:
      - "vmstorage"
    command:
      - '--storageNode=vmstorage:8400'
    ports:
      - 8480:8480
    networks:
      - docker_net
    restart: always
  vmselect:
    container_name: vmselect
    image: victoriametrics/vmselect:v1.25.1-cluster
    depends_on:
      - "vmstorage"
    command:
      - '--storageNode=vmstorage:8401'
    ports:
      - 8481:8481
    networks:
      - docker_net
    restart: always
volumes:
  promdata: {}
  strgdata: {}
networks:
  docker_net:
    driver: bridge
