api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  docker:
    type: docker_logs
  demo:
    type: demo_logs
    format: apache_common
    interval: 10
  vector_metrics:
    type: internal_metrics
transforms:
  msg_parser:
    type: remap
    inputs: [docker]
    source: |
      .message = parse_json(.message) ?? .message
sinks:
  elasticsearch:
    type: elasticsearch
    inputs: [demo, msg_parser]
    endpoints: [http://victorialogs:9428/insert/elasticsearch/]
    mode: bulk
    api_version: v8
    compression: gzip
    healthcheck:
      enabled: false
    request:
      headers:
        VL-Stream-Fields: source_type,label.com.docker.compose.service
        VL-Time-Field: timestamp
        VL-Msg-Field: message,msg,_msg,message.message,message.log
        AccountID: "0"
        ProjectID: "0"
  victoriametrics:
    type: prometheus_remote_write
    endpoint: http://victoriametrics:8428/api/v1/write
    inputs: [vector_metrics]
    healthcheck:
      enabled: false
