include:
 - ../compose-base.yml
services:
  logstash:
    build:
      context: .
    user: root
    restart: on-failure
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ${PWD}/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on: [victorialogs]
    ports:
      - "5140:5140"
