version: '3'

services:
  logstash:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on: [victorialogs]
    ports:
      - "5140:5140"

  victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v0.27.1-victorialogs
    volumes:
      - victorialogs-logstash-vl:/vlogs
    ports:
      - "9428:9428"
    command:
      - -storageDataPath=/vlogs

volumes:
  victorialogs-logstash-vl:
