version: "3"

services:
  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./config.yml:/etc/promtail/docker-config.yml:ro
    command: -config.file=/etc/promtail/docker-config.yml
    ports:
      - "5140:5140"

  vlogs:
    image: docker.io/victoriametrics/victoria-logs:v0.27.1-victorialogs
    volumes:
      - victorialogs-promtail-docker:/vlogs
    ports:
      - '9428:9428'
    command:
      - -storageDataPath=/vlogs

volumes:
  victorialogs-promtail-docker:
