version: '3'

services:
  # Run `make package-victoria-logs` to build victoria-logs image
  vlogs:
    image: docker.io/victoriametrics/victoria-logs:v0.35.0-victorialogs
    volumes:
      - vlogs:/vlogs
    ports:
      - '9428:9428'
    command:
      - -storageDataPath=/vlogs

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  du-exporter:
    image: ghcr.io/dundee/disk_usage_exporter/disk_usage_exporter-c4084307c537335c2ddb6f4b9b527422:latest
    restart: unless-stopped
    user: "root"
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - ./du/config.yml:/config.yml:ro
    command:
      - '--config=/config.yml'

  vmsingle:
    image: victoriametrics/victoria-metrics:v1.104.0
    ports:
      - '8428:8428'
    command:
      - -storageDataPath=/vmsingle
      - -promscrape.config=/promscrape.yml
      - -promscrape.maxScrapeSize=1Gb
    volumes:
      - vmsingle:/vmsingle
      - ./vmsingle/promscrape.yml:/promscrape.yml

  grafana:
    image: grafana/grafana:9.2.7
    depends_on: [vmsingle]
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards/
    restart: always

volumes:
  vlogs:
  vmsingle:
  grafanadata: {}
