version: "3"

services:
  filebeat-vlogs:
    image: docker.elastic.co/beats/filebeat:8.8.1
    user: root
    command:
      - "--strict.perms=false"
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on: [victorialogs]
    ports:
      - "5140:5140"

  victorialogs:
    image: docker.io/victoriametrics/victoria-logs:v0.27.1-victorialogs
    volumes:
      - victorialogs-filebeat-syslog-vl:/vlogs
    ports:
      - "9428:9428"
    command:
      - -storageDataPath=/vlogs

volumes:
  victorialogs-filebeat-syslog-vl:
