name: main
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: 1.17
        id: go
      - name: Code checkout
        uses: actions/checkout@master
      - name: Dependencies
        run: |
          make install-golint
          make install-errcheck
          make install-golangci-lint
      - name: Build
        env:
          GO111MODULE: on
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          make check-all
          git diff --exit-code
          make test-full
          make test-pure
          make test-full-386
          make victoria-metrics
          make victoria-metrics-pure
          make victoria-metrics-arm
          make victoria-metrics-arm64
          make vmutils
          GOOS=freebsd go build -mod=vendor ./app/victoria-metrics
          GOOS=freebsd go build -mod=vendor ./app/vmagent
          GOOS=freebsd go build -mod=vendor ./app/vmalert
          GOOS=freebsd go build -mod=vendor ./app/vmbackup
          GOOS=freebsd go build -mod=vendor ./app/vmrestore
          GOOS=freebsd go build -mod=vendor ./app/vmctl
          GOOS=openbsd go build -mod=vendor ./app/victoria-metrics
          GOOS=openbsd go build -mod=vendor ./app/vmagent
          GOOS=openbsd go build -mod=vendor ./app/vmalert
          GOOS=openbsd go build -mod=vendor ./app/vmbackup
          GOOS=openbsd go build -mod=vendor ./app/vmrestore
          GOOS=openbsd go build -mod=vendor ./app/vmctl
          GOOS=darwin go build -mod=vendor ./app/victoria-metrics
          GOOS=darwin go build -mod=vendor ./app/vmagent
          GOOS=darwin go build -mod=vendor ./app/vmalert
          GOOS=darwin go build -mod=vendor ./app/vmbackup
          GOOS=darwin go build -mod=vendor ./app/vmrestore
          GOOS=darwin go build -mod=vendor ./app/vmctl
          CGO_ENABLED=0 GOOS=windows go build -mod=vendor ./app/vmagent
      - name: Publish coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.txt

